[package]
name = "delegation-mock-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Sorin Petreasca <sorin.petreasca@multiversx.com>"]

[dev-dependencies]

[dependencies.delegation-mock]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.1"
