[package]
name = "delegation-mock"
version = "0.0.0"
authors = ["Sorin Petreasca <sorin.petreasca@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/delegation.rs"

[dependencies.multiversx-sc]
version = "0.54.4"

[dev-dependencies.multiversx-sc-scenario]
version = "0.54.4"
